[build]
builder = "docker"

[deploy]
startCommand = "bash safe_deploy.sh"

[[services]]
port = 8080
http = true

[variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
PORT = "8080"