services:
  - name: HostelHub
    build:
      builder: railpack
      build_command: "composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-bcmath --ignore-platform-req=ext-gd --ignore-platform-req=ext-sodium"
    start_command: "php artisan serve --host=0.0.0.0 --port=$PORT"
    deploy:
      runtime: V2