services:
  - name: HostelHub
    build:
      builder: railpack
      build_command: "composer install --no-dev --optimize-autoloader"
    start_command: "php -S 0.0.0.0:$PORT -t public"
    deploy:
      runtime: V2
